### ISSUE TITLE
How do you use this plugin in Angular?

### ISSUE THREAD

**Issue by arman-g** [nunof07/markdown-it-fontawesome#4]
Sorry, this is more a question than an issue. Can this component be used with Angular?
If yes than how?
Thank you in advance!

**Comment by nunof07** [comment]
This plugin can be used with [markdown-it](https://github.com/markdown-it/markdown-it). If you can run markdown-it with Angular, then you should be able to run this plugin. I don't see why not, but I don't have specific instructions to give you, I haven't used Angular in a long time.
